version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-18-214-140-149.compute-1.amazonaws.com
            port: '5432'
            database: d11lc86luovbsm
            ssl: true
            user: svfnysonbihote
            password: 4797124dc524d66c6f700a64e5b8417ce122e2d711cc38ce9bd5368d6bd82e04
            migrations: true
